<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>GujasPCFix</AssemblyName>
    <RootNamespace>GujasPCFix</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Include="assets\bg.jpg" LogicalName="GujasPCFix.bg.jpg" />
    <EmbeddedResource Include="assets\design-reference.png" LogicalName="GujasPCFix.games.png" />
    <EmbeddedResource Include="assets\dashboard-reference.png" LogicalName="GujasPCFix.dashboard.png" />
  </ItemGroup>
</Project>
